#!/bin/sh

if [ "$testdir" = "" ]; then
   echo You must use make check or make check-ada
   exit 1
fi

# Provide which replacement.
#
# type -p is missing from Solaris 2 /bin/sh and /bin/ksh (ksh88), but both
# ksh93 and bash have it.
# type output format differs between ksh88 and ksh93, so avoid it if
# type -p is present.  Unfortunately, HP-UX /bin/sh ignores -p with type.
# Fall back to whence which ksh88 and ksh93 provide, but bash does not.

which () {
    path=`type -p $* 2>/dev/null` && { echo $path | awk '{print $NF}'; return 0; }
    path=`type $* 2>/dev/null` && { echo $path | awk '{print $NF}'; return 0; }
    path=`whence $* 2>/dev/null` && { echo $path; return 0; }
    return 1
}

echo '#!/bin/sh' > host_gnatchop
echo exec /usr/bin/gnatchop --GCC=gcc-6 '$*' >> host_gnatchop

chmod +x host_gnatchop

echo '#!/bin/sh' > host_gnatmake
echo echo '$PATH' '$*' >> host_gnatmake
echo exec /usr/bin/gnatmake '$*' >> host_gnatmake

chmod +x host_gnatmake

# Set up environment to use the Ada compiler from the object tree

ROOT=`${PWDCMD-pwd}`
BASE=`cd $ROOT/../../..; ${PWDCMD-pwd}`
PATH=$BASE:$ROOT:$PATH
GCC_DRIVER="$BASE/xgcc"
TARGET=`${GCC_DRIVER} -v  2>&1 |grep '^Target:' | cut -d' ' -f2`
GNATTOOLS=`cd $BASE/../gnattools; ${PWDCMD-pwd}`
LIBGNATVSN=`cd $BASE/../${TARGET}/libgnatvsn; ${PWDCMD-pwd}`
LIBGNATPRJ=`cd $BASE/../${TARGET}/libgnatprj; ${PWDCMD-pwd}`
GCC="$BASE/xgcc -B$BASE/"
export PATH ADA_INCLUDE_PATH ADA_OBJECTS_PATH GCC_DRIVER GCC LD_LIBRARY_PATH
export GNATTOOLS LIBGNATVSN LIBGNATPRJ

# Limit the stack to 16MB for stack checking
ulimit -s 16384

exec $testdir/run_all.sh ${1+"$@"}
